<a href="https://colab.research.google.com/github/Muhammadfarasain34987/Amazon-Website-Clone/blob/main/pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# first to import numpy as np for numpy array operations
import numpy as np


In [4]:
# 1D Array
a = np.array([1, 2, 3])

# 2D Array
b = np.array([[1, 2], [3, 4]])

# 3D Array
c = np.array([[[1], [2]], [[3], [4]]])

print(a)
print(b)
print(c)

[1 2 3]
[[1 2]
 [3 4]]
[[[1]
  [2]]

 [[3]
  [4]]]


In [5]:
a.shape        # Shape of array
a.ndim         # Number of dimensions
a.dtype        # Data type
a.size         # Total number of elements
a.itemsize     # Size (in bytes) of each element
a.nbytes       # Total bytes used


24

In [6]:
>>> np.zeros((3,4)) #Create an array of zeros
>>> np.ones((2,3,4),dtype=np.int16) #Create an array of ones
>>> d = np.arange(10,25,5)#Create an array of evenly spaced values (step value)
>>> np.linspace(0,2,9) #Create an array of evenlyspaced values (number of samples)
>>> e = np.full((2,2),7)#Create a constant array
>>> f = np.eye(2) #Create a 2X2 identity matrix
>>> np.random.random((2,2)) #Create an array with random values
>>> np.empty((3,2)) #Create an empty array


array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

In [7]:
a=np.zeros((2,3))
print(a)
print()
b=np.zeros((8,9))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
a=np.ones((3,4),dtype=int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
arr = np.arange(6)       # [0 1 2 3 4 5]
arr.reshape(2, 3)        # (2 rows, 3 columns)
arr.flatten()            # Flatten to 1D
arr.resize((3, 2))       # Resizes in-place

In [10]:
import numpy as np

arr = np.arange(6)
print("Original array:", arr)
# Output: [0 1 2 3 4 5]

Original array: [0 1 2 3 4 5]


In [11]:
arr = np.arange(6)
arr.resize((3, 2))  # In-place
print("Resized in-place to (3, 2):\n", arr)

Resized in-place to (3, 2):
 [[0 1]
 [2 3]
 [4 5]]


In [12]:
arr = np.arange(6)
arr.resize((3, 2))  # In-place
print("Resized in-place to (3, 2):\n", arr)


Resized in-place to (3, 2):
 [[0 1]
 [2 3]
 [4 5]]


In [13]:
# Indexing
arr = np.array([10, 20, 30, 40, 50])
print("Element at index 2:", arr[2])

Element at index 2: 30


In [14]:
# Slicing
print("Elements from index 1 to 3:", arr[1:4])
# Output: [20 30 40]

Elements from index 1 to 3: [20 30 40]


In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c=a + b       # Element-wise addition
d=a * b       # Element-wise multiplication
e=a / b       # Division
f=a ** 2      # Power

# Simple OPerations
print(c)
print(d)
print(e)
print(f)

# np operations
np.add(a, b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


array([5, 7, 9])

In [16]:
np.multiply(a, b) # Multiply a and b

array([ 4, 10, 18])

In [17]:
np.exp(a)       # Exponential


array([ 2.71828183,  7.3890561 , 20.08553692])

In [18]:
 np.sqrt(a)      # Square root

array([1.        , 1.41421356, 1.73205081])

In [19]:
# sum functions
arr = np.array([[1, 2, 3], [4, 5, 6]])

np.sum(arr)

np.int64(21)

In [20]:
np.mean(arr) # mean of array

np.float64(3.5)

In [21]:
# minimum element in array
np.min(arr)


np.int64(1)

In [ ]:
# find max element in array
np.max(arr)


np.int64(6)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
a[mask]

array([4, 5])

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

a + b   # Broadcasting b across rows

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
np.random.seed(0)
np.random.rand(2, 3)           # Uniform [0, 1)
np.random.randn(2, 3)          # Standard normal
np.random.randint(0, 10, size=(2, 3))  # Random integers

np.random.shuffle(arr)         # Shuffle array in-place


In [ ]:
import numpy as np

np.random.seed(0)
rand_uniform = np.random.rand(2, 3)
print("Random uniform [0, 1):\n", rand_uniform)

Random uniform [0, 1):
 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [ ]:
a=np.arange(1,13).reshape(3,4)
b=np.arange(13,25).reshape(3,4)
s=np.concatenate((a,b),axis=1)
s

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [2]:
a=np.arange(1,7)
print(a.shape)
print()
print(a)
print()
print(a[np.newaxis,:].shape)
print()
print(a[np.newaxis,:])
s=a[np.newaxis,:]
s[np.newaxis,:]

NameError: name 'np' is not defined

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 6)

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
np.nonzero(a)
print(a[np.nonzero(a)])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a=np.arange(1,4)
b=np.arange(5,8)
print(a)
print()
print(b)
print()
c=list(zip(a,b))
for i in c:
    print(i)

[1 2 3]

[5 6 7]

(np.int64(1), np.int64(5))
(np.int64(2), np.int64(6))
(np.int64(3), np.int64(7))


In [ ]:
a=np.arange(1,13).reshape(3,4)
b=np.arange(13,25).reshape(3,4)
print(np.vstack((a,b)))
print()
print(np.hstack((a,b)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [ ]:
a=np.arange(1,13)
print(np.sum(a))
print()
b=np.arange(13,25)
np.sum([a,b])

78



np.int64(300)

In [ ]:
a=np.array([1,2,3,2,1,4,2,5,35,33,5,22,3,1,43])
print(np.unique(a,return_index=True))

(array([ 1,  2,  3,  4,  5, 22, 33, 35, 43]), array([ 0,  1,  2,  5,  7, 11,  9,  8, 14]))


In [ ]:
a=np.arange(1,14)
print(np.flip(a))
print()
b=np.arange(1,25).reshape(4,6)
print(b)
print()
print(np.flip(b))
print(b.shape)
c=b[np.newaxis,:]
print()
print(c)
np.flip(c)

[13 12 11 10  9  8  7  6  5  4  3  2  1]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]
(4, 6)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


array([[[24, 23, 22, 21, 20, 19],
        [18, 17, 16, 15, 14, 13],
        [12, 11, 10,  9,  8,  7],
        [ 6,  5,  4,  3,  2,  1]]])

In [1]:
a=np.arange(12).reshape(3,4)
print(a)
print()
print(a.T)
a=np.arange(18).reshape(2,3,3)
print()
print(a)
print()
print(a.T)

NameError: name 'np' is not defined

In [ ]:
np.flip(c[0,1])

array([12, 11, 10,  9,  8,  7])

In [ ]:
print(np.eye(5))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
x = np.arange(5)
row=x[np.newaxis,:]
col=x[:,np.newaxis]
print(row+col)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [ ]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
row=np.array([[1,1],[3,3]])
col=np.array([[0,2],[0,2]])
x[row,col]

array([[ 3,  5],
       [ 9, 11]])

In [ ]:
x = np.arange(35).reshape(5, 7)
b=x>20
b[:,5]

array([False, False, False,  True,  True])

In [ ]:
x = np.array([[0, 1], [1, 1], [2, 2]])
x.sum(-1)

array([1, 2, 4])

In [ ]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
x[x.sum(-1) % 2 == 0]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [ ]:
a=np.empty((3,4))
a

array([[4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323, 3.5e-323, 4.0e-323],
       [4.4e-323, 4.9e-323, 5.4e-323, 5.9e-323]])

In [ ]:
a=np.arange(1,50)
np.where(a>45)

(array([45, 46, 47, 48]),)

In [ ]:
replace_0=np.where(a>47,0,a)
replace_0

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,  0,  0])

In [ ]:
replace_even_0=np.where(a%2==0,0,a)
replace_even_0

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0, 21,  0, 23,  0, 25,  0, 27,  0, 29,  0, 31,  0, 33,  0,
       35,  0, 37,  0, 39,  0, 41,  0, 43,  0, 45,  0, 47,  0, 49])

In [ ]:
np.percentile(a,100)

np.float64(49.0)

In [ ]:
a=np.array([1,2,3,4,1,5,2,6,3,6,2,51,3,5,1,512,5,2,4,2,5,7,8,3,1,3,21,1,1,3,1,4,1,4,1,3,1,2,5,2,5,63,5,3,6,33,655,4,4,4,3,3,3,3,35,5,5,6,1,7,7,8,1,8,7,5,4,3,3])
np.histogram(a,bins=[0,50,1000])

(array([65,  4]), array([   0,   50, 1000]))

In [ ]:
x=np.arange(36).reshape(2,3,6)
print(x)
print(x[0,Ellipsis])
print()
print(x[:, :,0])
print()
print(x[:, np.newaxis, :,:])
print()
print(x[:, np.newaxis, :,:].shape)
print()
print(x[np.newaxis,:, :,:])
print()
print(x[np.newaxis,:,:].shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

[[ 0  6 12]
 [18 24 30]]

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]]]


 [[[18 19 20 21 22 23]
   [24 25 26 27 28 29]
   [30 31 32 33 34 35]]]]

(2, 1, 3, 6)

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]]

  [[18 19 20 21 22 23]
   [24 25 26 27 28 29]
   [30 31 32 33 34 35]]]]

(1, 2, 3, 6)


In [ ]:
x=np.arange(5)
print(x[:,np.newaxis]+x[np.newaxis,:])
print()

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]



In [ ]:
x=np.arange(25).reshape(5,5)
print(x)
print()
row=np.array([[1,1],[3,3]])
col=np.array([[1,-1],[1,-1]])
print(x[row,col])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 6  9]
 [16 19]]
